[workspace]
# Using version 2 to avoid unifying features. For more info, read:
#   https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = ["crates/blockifier"]

[workspace.package]
version = "0.4.0-rc6"
edition = "2021"
repository = "https://github.com/starkware-libs/blockifier/"
license = "Apache-2.0"
license-file = "LICENSE"

[workspace.dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.0-alpha.7"
ark-secp256k1 = "0.4.0"
ark-secp256r1 = "0.4.0"
assert_matches = "1.5.0"
cached = "0.44.0"
cairo-felt = { git = "https://github.com/kkrt-labs/cairo-vm.git", branch = "v0.9.1", default-features = false }
cairo-lang-casm = { git = "https://github.com/kkrt-labs/cairo.git", branch = "v2.4.0", default-features = false }
cairo-lang-runner = { git = "https://github.com/kkrt-labs/cairo.git", branch = "v2.4.0", default-features = false }
cairo-lang-starknet = { git = "https://github.com/kkrt-labs/cairo.git", branch = "v2.4.0", default-features = false }
cairo-lang-utils = { git = "https://github.com/kkrt-labs/cairo.git", branch = "v2.4.0", default-features = false }
cairo-vm = { git = "https://github.com/kkrt-labs/cairo-vm.git", branch = "v0.9.1", default-features = false, features = [
  "print",
] }
criterion = "0.3"
ctor = "0.2.0"
derive_more = "0.99.17"
indexmap = "2.1.0"
itertools = "0.10.3"
keccak = "0.1.3"
log = "0.4"
num-bigint = "0.4"
num-integer = "0.1.45"
num-traits = "0.2"
rstest = "0.17.0"
papyrus_storage = "0.2.0-rc2"
phf = { version = "0.11", features = ["macros"] }
pretty_assertions = "1.2.1"
pyo3 = "0.19.1"
pyo3-log = "0.8.1"
serde = "1.0.184"
serde_json = "1.0.81"
sha3 = "0.10.6"
starknet_api = "0.6.0-rc2"
starknet-crypto = "0.5.1"
strum = "0.24.1"
strum_macros = "0.24.3"
test-case = "2.2.2"
tempfile = "3.7.0"
thiserror = "1.0.37"

[workspace.lints.rust]
warnings = "deny"
future-incompatible = "deny"
nonstandard-style = "deny"
rust-2018-idioms = "deny"
unused = "deny"
